### PR TITLE
Update copyrights

### PR DESCRIPTION
**Pull request by vtnate**
- Copy doc_templates folder from geojson-gem
- Update copyrights with openstudio rake task
    - Exclude `example_project/resources/hpxml-measures` because it is subtreed from OS-HPXML
    - Exclude `example_project/measures/` because those are not exclusively UO measures
- Manually update `Rakefile`, `LICENSE.md`, and `developer_nrel_key.rb` because they are above the dir with `doc_templates` that get run automatically by the rake task. The rake task failed when that templates folder was in the root dir.

### CODE REVIEW

**Comment by vtnate** [comment]
@joseph-robertson I ran `rake openstudio:update_copyright` on this repo, to include 2022. It updated a bunch of stuff from the hpxml subtree. Is that appropriate? Should I do something different?

**Comment by joseph-robertson** [comment]
From the perspective of subtree, I would say no you don't want to touch any of those files- it will create conflicts for future pulls from OS-HPXML. From the perspective of copyrights on everything "URBANopt", I'm not sure if we _can_ ignore these files.

**Comment by vtnate** [comment]
Looks like none of those hpxml files had copyrights until I ran this task. Should they have NREL copyrights at least?

**Comment by joseph-robertson** [comment]
I asked for Scott's opinion. He says that he thinks it's nice to have but not required. openstudio-standards doesn't seem to do it either.

**Comment by vtnate** [comment]
Thanks Joe. I'll revert the changes to everything in that subtree.

**Review by kflemin — APPROVED** [review]

**Pull request merged**
